#!/usr/bin/env node
/* VOLÀ — fetch the typefaces and serve them from this domain.
 *
 *   node tools/fonts-fetch.mjs
 *   node tools/fonts-fetch.mjs --dry     report what it would fetch
 *
 * Why this exists.
 *
 * Every page linked its stylesheet from fonts.googleapis.com, which meant the
 * browser asked Google for it before rendering anything — sending the reader's
 * IP address and user-agent to a company they have no relationship with,
 * before they had clicked a thing. Every other third party on this site is
 * reached because the reader did something: bought, wrote, subscribed. This
 * one happened to everybody, on every page, unasked.
 *
 * German courts have held that unlawful without consent (LG München I,
 * 3 O 17493/20), and the site's own privacy page had to list it as the one
 * transfer nobody chose. The fix is to hold the files ourselves — three
 * hundred kilobytes, and the request never leaves this domain.
 *
 * It is also faster. The old chain was: HTML → DNS + TLS to googleapis →
 * CSS → DNS + TLS to gstatic → font. Two extra connections on the critical
 * path, both blocking text from painting. Now the font files sit beside the
 * stylesheet that asks for them.
 *
 * Both families are licensed under the SIL Open Font License 1.1, which
 * permits redistribution as long as the licence travels with them — so it is
 * fetched too and written beside the files.
 *
 * No dependencies. Node 18+ for global fetch.
 */

import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'assets/fonts');
const DRY = process.argv.includes('--dry');

/* The exact stack the site is set in — kept here so this file, and not a URL
   buried in fifteen <head>s, is where the typography is declared. */
const FAMILIES = 'family=Cormorant:ital,wght@0,300;0,400;0,500;1,300' +
                 '&family=Montserrat:wght@400;500;600';

/* Google splits each face into a dozen unicode-range subsets. This site is
   English and Italian; latin and latin-ext cover both, and cover the accented
   names in the mill records and the reviews. Taking cyrillic, greek and
   vietnamese as well would quadruple the weight for glyphs nothing renders. */
const KEEP = new Set(['latin', 'latin-ext']);

/* Google serves woff2 only to a user-agent it believes supports it. */
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

/* ────────────────────────────────────────────────────────────── fetching ── */
async function css() {
  const url = 'https://fonts.googleapis.com/css2?' + FAMILIES + '&display=swap';
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts returned ${res.status} ${res.statusText}`);
  return res.text();
}

/* Each @font-face arrives preceded by a /* subset *\/ comment. Parse the block
   rather than the URL, because the subset name is the only thing that says
   whether a file is worth 30KB of this site's weight. */
function parse(text) {
  const faces = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let m;
  while ((m = re.exec(text))) {
    const subset = m[1];
    const body = m[2];
    const pick = (k) => (body.match(new RegExp(k + ':\\s*([^;]+);')) || [, ''])[1].trim();
    const url = (body.match(/url\(([^)]+)\)/) || [, ''])[1];
    faces.push({
      subset,
      family: pick('font-family').replace(/['"]/g, ''),
      style: pick('font-style'),
      weight: pick('font-weight'),
      range: pick('unicode-range'),
      url
    });
  }
  return faces;
}

/* A stable, readable filename: montserrat-600-normal-latin.woff2. Google's own
   names are content hashes, which tell a maintainer nothing and change on
   every release for reasons that are never ours. */
function filename(f) {
  return [f.family.toLowerCase().replace(/\s+/g, '-'), f.weight, f.style, f.subset]
    .join('-') + '.woff2';
}

async function download(f) {
  const res = await fetch(f.url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${f.url} returned ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

/* ───────────────────────────────────────────────────────────── emitting ── */
function stylesheet(faces) {
  const head =
`/* VOLÀ — the typefaces, served from this domain.
   GENERATED by tools/fonts-fetch.mjs on ${new Date().toISOString()}
   Do not edit by hand — change FAMILIES in that tool and re-run it.

   These were loaded from fonts.googleapis.com, which sent every reader's IP
   address to Google before the first paint of every page, without their
   asking. They are held here instead. See assets/fonts/OFL.txt for the
   licence, which permits exactly this.

   font-display: swap — the text paints immediately in the fallback and
   reflows when the face arrives. A reader who never sees the words is worse
   served than one who sees them twice. */

`;

  return head + faces.map((f) => {
    return `/* ${f.family} ${f.weight} ${f.style} — ${f.subset} */
@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('../fonts/${filename(f)}') format('woff2');
  unicode-range: ${f.range};
}`;
  }).join('\n\n') + '\n';
}

/* ───────────────────────────────────────────────────────────────── main ── */
try {
  console.log('\n  Reading the face list from Google …');
  const all = parse(await css());
  const faces = all.filter((f) => KEEP.has(f.subset));

  if (!faces.length) throw new Error('No matching faces — did the CSS format change?');

  const skipped = [...new Set(all.filter((f) => !KEEP.has(f.subset)).map((f) => f.subset))];
  console.log(`  ${all.length} faces offered · keeping ${faces.length} (${[...KEEP].join(', ')})`);
  if (skipped.length) console.log(`  skipping ${skipped.join(', ')} — nothing on this site renders them`);

  if (DRY) {
    for (const f of faces) console.log(`    ${filename(f)}`);
    console.log('\n  --dry: nothing written.\n');
  } else {
    await writeAll(faces);
  }
} catch (err) {
  console.error(`\n  Failed: ${err.message}\n`);
  process.exitCode = 1;
}

async function writeAll(faces) {
  await mkdir(OUT, { recursive: true });

  let total = 0;
  for (const f of faces) {
    const buf = await download(f);
    await writeFile(join(OUT, filename(f)), buf);
    total += buf.length;
    console.log(`    ${filename(f)}  ${(buf.length / 1024).toFixed(1)} KB`);
  }

  /* The licence travels with the files. This is a condition of the OFL, not a
     courtesy — redistributing the fonts without it is a breach. */
  const ofl = await fetch('https://raw.githubusercontent.com/google/fonts/main/ofl/montserrat/OFL.txt');
  if (ofl.ok) {
    const text = await ofl.text();
    await writeFile(join(OUT, 'OFL.txt'),
      'Cormorant and Montserrat are licensed under the SIL Open Font License,\n' +
      'Version 1.1, reproduced below. Both are Copyright the Cormorant Project\n' +
      'Authors and the Montserrat Project Authors respectively.\n\n' +
      'They are served from this domain rather than from Google Fonts. The OFL\n' +
      'permits that; it requires this file to travel with them.\n\n' +
      '-------------------------------------------------------------------\n\n' + text);
    console.log('    OFL.txt');
  } else {
    console.log('  ⚠  Could not fetch OFL.txt. Add it by hand — the licence requires it.');
  }

  await writeFile(join(ROOT, 'assets/css/fonts.css'), stylesheet(faces), 'utf8');

  console.log(`\n  ${(total / 1024).toFixed(0)} KB of fonts, and not one byte of it from Google.`);
  console.log(`  Wrote assets/css/fonts.css and ${faces.length} files to assets/fonts/\n`);
}
